version: '2'

services:

  # nginx:
  #   restart: always
  #   build: ./nginx
  #   ports:
  #     - "80:80"
  #   links:
  #     - web:web
  #   depends_on:
  #     - redis

  web:
    build:
      context: ./flask-app
      dockerfile: Dockerfile
    restart: always
    ports:
     - "5000:5000"
    depends_on:
      - redis

  worker:
    build:
      context: ./flask-celery
      dockerfile: Dockerfile
    depends_on:
      - redis

  flower:
    image: placr/flower
    ports:
     - "5555:5555"
    links:
      - redis:redis

  redis:
    image: redis

  redis_commander:
    image: tenstartups/redis-commander
    container_name: dj_redis_commander
    command: --redis-host redis
    links:
      - redis:redis
    ports:
      - "8081:8081"
